### ISSUE TITLE
SBDRxChannelEventListener is not public class

### ISSUE THREAD

**Issue by winnisx7** [intoxicated/RxSendBirdSDK#2]
SBDChannelDelegate의 기능을 SBDRxChannelEventListener를 이용해서 사용하라는 코드같은데 접근이 불가능해요
혹시 제가 코드를 잘못 이해한건가요?
(닉네임 보니 한국인이신 것 같아서 한글로 적어봅니다)

**Comment by intoxicated** [comment]
어떻게 접근하고있는지 코드들 보여주시면 도움드릴수있을것 같습니다

**Comment by winnisx7** [comment]
SBDRxChannelEventListener.receiveMessage() 를 사용하려고 하는데, 클래스와 메소드가 public으로 되어 있지 않아서 접근이 안됩니다.

**Comment by intoxicated** [comment]
patch 했습니다~ 이게 작년에 제가 만든거라 그동안 나온 피쳐 혹은 변경사항이 아직 적용이 안되어있습니다. 추후 업데이트 할 예정입니다
